FROM pytorch/pytorch:2.5.0-cuda11.8-cudnn9-runtime
# FROM pytorch/pytorch:2.5.0-cuda12.4-cudnn9-devel

#RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
#RUN pip3 install monai==1.2.0

RUN apt update && apt install -y git && git clone https://github.com/Project-MONAI/GenerativeModels.git && cd GenerativeModels && git reset --hard 7428fce193771e9564f29b91d29e523dd1b6b4cd && python setup.py install

# COPY ./weights/model_axial.pt /inpainting/weights/model_axial.pth
# COPY ./weights/model_coronal.pt /inpainting/weights/model_coronal.pth
# COPY ./weights/model_sagittal.pt /inpainting/weights/model_sagittal.pth

RUN wget https://zenodo.org/records/14497226/files/model_axial.pt -O /inpainting/weights/model_axial.pth
RUN wget https://zenodo.org/records/14497226/files/model_coronal.pt -O /inpainting/weights/model_coronal.pth
RUN wget https://zenodo.org/records/14497226/files/model_sagittal.pt -O /inpainting/weights/model_sagittal.pth

COPY lit /inpainting/lit
COPY run_lit.sh /inpainting/run_lit.sh

ENV INPAINTING_DIR=/inpainting

ENTRYPOINT ["/bin/bash", "/inpainting/run_lit.sh"]

RUN mkdir -p /transformers_cache
ENV HF_HOME=/transformers_cache
RUN chmod -R a+w /transformers_cache

RUN mkdir -p /inpainting/.matplotlib
ENV MPLCONFIGDIR=/inpainting/.matplotlib
RUN chmod -R a+w /inpainting/.matplotlib

RUN mkdir -p /inpainting/.triton
ENV TRITON_CACHE_DIR=/inpainting/.triton
RUN chmod -R a+w /inpainting/.triton


RUN pip3 install matplotlib nibabel scipy


WORKDIR /inpainting
